'use strict';

const { irreversibleMigration } = require('../utils');

module.exports = {
  up: async (queryInterface) => {
    await queryInterface.sequelize.query(`
        UPDATE public.owners
		    SET description = '{
                "fr":"imagineRio est un atlas numérique consultable qui illustre le développement social et urbain de Rio de Janeiro, tel qu''il a existé et tel qu''il a été imaginé. Des vues, des cartes, des plans et des antennes - provenant d''archives iconographiques, cartographiques et architecturales - sont localisées à la fois dans le temps et dans l''espace. Dans Smapshot, la topographie changeante dans le temps est empruntée à imagineRio afin que les utilisateurs puissent géolocaliser les images de Rio de Janeiro créées par les photographes du XIXe et du début du XXe siècle. Une fois géolocalisée, la visionneuse 3D permet une expérience de visionnement raffinée, y compris la possibilité d''échanger des modèles de terrain pour l''examen et la comparaison de différents moments dans le temps. Les photographies sont disponibles dans la collection de l''Instituto Moreira Salles.",
                "en":"imagineRio is a searchable digital atlas that illustrates the social and urban development of Rio de Janeiro, as it existed and as it was imagined. Views, maps, plans and aerials –from iconographic, cartographic, and architectural archives – are located in both time and space. In Smapshot, the temporally changing topography is borrowed from imagineRio so that users can geolocalize images of Rio de Janeiro created by 19th- and early 20th-century photographers. Once geolocalized, the 3D viewer allows for a refined viewing experience, including the ability to swap terrain models for examination and comparison of different moments in time. Photographs are made available from the collection of the Instituto Moreira Salles.",
                "de":"imagineRio ist ein durchsuchbarer digitaler Atlas, der die soziale und städtische Entwicklung von Rio de Janeiro, wie sie existierte und wie sie sich vorgestellt wurde, veranschaulicht. Ansichten, Karten, Pläne und Luftbilder - aus ikonografischen, kartografischen und architektonischen Archiven - befinden sich sowohl in Zeit und Raum. In Smapshot wird die sich zeitlich verändernde Topographie von imagineRio entlehnt, so dass Benutzer Bilder von Rio de Janeiro, die von Fotografen des 19. und frühen 20. Jahrhunderts geschaffen wurden, geolokalisieren können. Nach der Geolokalisierung ermöglicht der 3D-Viewer ein verfeinertes Betrachtungserlebnis, einschließlich der Möglichkeit, Geländemodelle zur Untersuchung und zum Vergleich verschiedener Momente in der Zeit auszutauschen. Die Fotografien werden aus der Sammlung des Instituto Moreira Salles zur Verfügung gestellt.",
                "it":"imagineRio è un atlante digitale ricercabile che illustra lo sviluppo sociale e urbano di Rio de Janeiro, così come esisteva e come era stato immaginato. Vedute, mappe, planimetrie e antenne - provenienti da archivi iconografici, cartografici e architettonici - sono collocate sia nel tempo che nello spazio. In Smapshot, la topografia che cambia nel tempo è presa in prestito da imagineRio, in modo che gli utenti possano geolocalizzare le immagini di Rio de Janeiro create dai fotografi del XIX e inizio del XX secolo. Una volta geolocalizzato, il visualizzatore 3D consente un''esperienza di visualizzazione raffinata, compresa la possibilità di scambiare modelli del terreno per l''esame e il confronto di diversi momenti nel tempo. Le fotografie sono rese disponibili dalla collezione dell''Instituto Moreira Salles.",
                "pt": "imagineRio é um atlas digital pesquisável que ilustra o desenvolvimento urbano e social do Rio de Janeiro, tal como existiu e como foi imaginado. Vistas, mapas, plantas baixas e fotografias aéreas – pinçadas de acervos iconográficos, cartográficos e arquitetônicos – são localizados tanto no tempo quanto no espaço. No Smapshot, emprestamos as mudanças topográficas do imagineRio para que os usuários possam geolocalizar imagens do Rio de Janeiro criadas por fotógrafos do século 19 e início do século 20. Uma vez localizadas, o visualizador 3D possibilita uma experiência refinada de visualização, incluindo a possibilidade de substituir modelos de terreno para examinar e comparar diferentes pontos no tempo. As fotografias disponibilizadas provêm do acervo do Instituto Moreira Salles.",
                "ja": "imagineRioは、リオデジャネイロの社会的・都市的発展を、実際に存在したものとして、また想像されたものとして描く、検索可能なデジタルアトラスです。図像、地図、図面、航空写真は、図像学、地図学、建築学のアーカイブから収集され、時間と空間の両方に位置づけられています。Smapshotでは、imagineRioから時間の経過とともに変化する地形を借用し、ユーザーが19世紀および20世紀初頭の写真家によって撮影されたリオデジャネイロの画像を地理的に位置づけることができます。地理的位置が特定されると、3Dビューアーにより、異なる時代の検証と比較のために地形モデルを切り替える機能を含む、洗練された表示体験が可能になります。写真はInstituto Moreira Sallesのコレクションで利用可能です。"
            }'
        WHERE owners.id = 11;
    `);
  },
  down: irreversibleMigration(__filename)
};
