FROM smapshot/base

LABEL maintainer="smapshot@heig-vd.ch"

# The application will be mounted into this directory.
WORKDIR /usr/src/app

COPY package.json package-lock.json /usr/src/app/
RUN npm ci

COPY ./ /usr/src/app/

ENV NODE_ENV=test

CMD [ "npm", "test" ]
